image: go1.3
git:
  path: epek.io/cmd
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
- echo "CI $CI"
- echo "DRONE $DRONE"
- echo "DRONE_REPO_SLUG $DRONE_REPO_SLUG" 
- echo "DRONE_BUILD_URL $DRONE_BUILD_URL"
- echo "DRONE_BUILD_DIR $DRONE_BUILD_DIR"
- echo "DRONE_BUILD_NUMBER: $DRONE_BUILD_NUMBER"
- echo "DRONE_COMMIT: $DRONE_COMMIT"
- echo "DRONE_BRANCH: $DRONE_BRANCH"

- echo "JOB_NAME: $JOB_NAME"
- echo "WORKSPACE: $WORKSPACE"
- echo "BUILD_URL: $BUILD_URL"
- echo "BUILD_DIR: $BUILD_DIR"
- echo "BUILD_ID: $BUILD_ID"
- echo "GIT_COMMIT: $GIT_COMMIT"
- echo "GIT_BRANCH: $GIT_BRANCH"
